spring:
    datasource:
      url: jdbc:mysql://localhost:3306/sp_micro?useSSL=false&allowPublicKeyRetrieval=true&useLegacyDatetimeCode=false
      username: root
      password: root1234
      driver-class-name: com.mysql.cj.jdbc.Driver
    servlet:
        multipart:
            max-file-size: 100MB
            max-request-size: 100MB
    jpa:
       show-sql: true
       hibernate:
            ddl-auto: create-drop
            naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
       properties:
        hibernate:
            dialect: org.hibernate.dialect.MySQL5InnoDBDialect
       defer-datasource-initialization: true
    sql:
        init:
            mode: always